# This workflow will check any code for Exceptions or other inconsistencies in code.

name: Lint Python.
on: [push, pull_request]


jobs:
  lint_python:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Set up Python
        uses: actions/setup-python@v2

      - name: Install dependcies
        run: pip install flake8, isort, black

      - name: Lint python with flake8
        run: |
          flake8 . --count --select=E9,F63,F7,F82,F632,E0401 --max-line-length=120 --show-source --statistics

      - name: Check formatting with isort
        run: python -m isort steam tests --diff --check-only

      - name: Check formatting with black
        uses: psf/black@20.8b1
